### ISSUE TITLE
Add `ENV` variables template and steps to set it up in `README`.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/placement_tracker_server#2]
The 4 env vars need to be declared in a `.env` file locally in order to run backend code. Add this step to `README`.

```env
DB_HOST=
DB_USER=
DB_PASSWORD=
DB_NAME=
```

**Comment by adithya-menon-r** [comment]
Hey @Ashrockzzz2003, I would like to solve this issue.

**Comment by Ashrockzzz2003** [comment]
@adithya-menon-r I'm reserving this for 1st-years!

**Comment by Ashrockzzz2003** [comment]
Assigned @BIJJUDAMA
